github:
  user_or_org: wasontech

channels:
  targets:
    - [wasontech, main]

provider:
  linux: github_actions
  osx: None
  win: None
  linux_aarch64: None
  linux_ppc64le: None

github_actions:
  store_build_artifacts: True